"""add clean_sheets to player

Revision ID: 0bb96f9c898f
Revises: c1d238f27e1c
Create Date: 2026-02-14 21:12:13.125711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb96f9c898f'
down_revision = 'c1d238f27e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clean_sheets', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('clean_sheets')

    # ### end Alembic commands ###
